/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create the first administrator */
        post: operations["setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start an administrator session */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the active session */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the active session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users as an administrator */
        get: operations["listUsers"];
        put?: never;
        /** Create a user as an administrator */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change a user's role or active state */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects visible to the active principal */
        get: operations["listProjects"];
        put?: never;
        /** Create a project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Activate or deactivate a project */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/api/projects/{id}/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active SDK keys and DSNs (administrator only) */
        get: operations["listProjectKeys"];
        put?: never;
        /** Issue a project DSN key */
        post: operations["createProjectKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a project key */
        delete: operations["revokeProjectKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Issues for an active project */
        get: operations["listIssues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read scrubbed mutable Issue metadata */
        get: operations["getIssue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change Issue status with revision compare-and-swap */
        patch: operations["updateIssue"];
        trace?: never;
    };
    "/api/issues/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List occurrence identities without raw payload hydration */
        get: operations["listIssueOccurrences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/events/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hydrate the scrubbed payload for one Issue occurrence */
        get: operations["getIssueOccurrence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search projected log and error rows in a stable read snapshot */
        get: operations["listLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream received records in ingest sequence order
         * @description Uses a fixed absolute received-time scope. Each record and completed scan
         *     checkpoint carries a signed SSE id. Reconnect with Last-Event-ID or the
         *     equivalent resume query parameter.
         */
        get: operations["streamLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explore/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search projected log and error rows with a JSON request */
        post: operations["searchLogs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/records/{detail_token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hydrate one scrubbed stored payload using its opaque detail token */
        get: operations["getRecord"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/records/{detail_token}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find authorized records related to one signed record identity */
        get: operations["getRelatedRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active alert configurations */
        get: operations["listAlerts"];
        put?: never;
        /** Create an alert configuration */
        post: operations["createAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Soft-delete an alert and cancel pending deliveries */
        delete: operations["deleteAlert"];
        options?: never;
        head?: never;
        /** Replace an alert configuration using revision compare-and-swap */
        patch: operations["updateAlert"];
        trace?: never;
    };
    "/api/alert-deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect recent alert delivery outcomes */
        get: operations["listAlertDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alert-deliveries/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry one failed delivery with its stable identity */
        post: operations["retryAlertDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read implementation and readiness status */
        get: operations["getSystemStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run read-only metadata and shard consistency checks */
        get: operations["getSystemDoctor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explore/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aggregate an authorized read snapshot */
        post: operations["aggregate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listReplays"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFeedback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay-pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReplayMaps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replays/{project}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReplay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replays/{project}/{id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["analyzeReplay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replays/{project}/{id}/segments/{segment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReplayRecording"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SetupRequest: {
            token: string;
            /** Format: email */
            email: string;
            password: string;
        };
        Credentials: {
            email: string;
            password: string;
        };
        LoginResponse: {
            csrf_token: string;
        };
        Session: {
            id: string;
            email: string;
            /** @enum {string} */
            role: "admin" | "member";
            csrf_token: string;
        };
        User: {
            id: string;
            email: string;
            /** @enum {string} */
            role: "admin" | "member";
            is_active: boolean;
        };
        UserList: {
            items: components["schemas"]["User"][];
        };
        CreateUserInput: {
            /** Format: email */
            email: string;
            password: string;
            /** @enum {string} */
            role: "admin" | "member";
        };
        UpdateUserInput: {
            /** @enum {string} */
            role?: "admin" | "member";
            is_active?: boolean;
        };
        Project: {
            id: string;
            slug: string;
            name: string;
            is_active: boolean;
        };
        ProjectList: {
            items: components["schemas"]["Project"][];
        };
        ProjectInput: {
            slug: string;
            name: string;
        };
        ProjectUpdate: {
            is_active: boolean;
        };
        IdResponse: {
            id: string;
        };
        ProjectKey: {
            id: string;
            public_key: string;
            /** Format: uri */
            dsn: string;
        };
        /** @description Signed 64-bit integer encoded as a decimal string. */
        Int64String: string;
        /** @description Positive 64-bit integer encoded as a decimal string. */
        PositiveDecimalString: string;
        /** @description Non-negative 64-bit integer encoded as a decimal string. */
        NonNegativeDecimalString: string;
        IssueId: string;
        /** @enum {string} */
        IssueStatus: "unresolved" | "resolved" | "ignored";
        Issue: {
            id: components["schemas"]["IssueId"];
            project_id: components["schemas"]["PositiveDecimalString"];
            fingerprint: string;
            fingerprint_version: components["schemas"]["PositiveDecimalString"];
            title: string;
            culprit: string | null;
            level: string;
            status: components["schemas"]["IssueStatus"];
            first_seen_us: components["schemas"]["Int64String"];
            last_seen_us: components["schemas"]["Int64String"];
            occurrence_count: components["schemas"]["PositiveDecimalString"];
            first_release: string | null;
            last_release: string | null;
            resolved_at_us: components["schemas"]["Int64String"] | null;
            resolved_through_ingest_seq: components["schemas"]["NonNegativeDecimalString"] | null;
            revision: components["schemas"]["NonNegativeDecimalString"];
            created_at_us: components["schemas"]["Int64String"];
            updated_at_us: components["schemas"]["Int64String"];
        };
        IssueCursor: {
            last_seen_us: components["schemas"]["Int64String"];
            id: components["schemas"]["IssueId"];
        };
        IssuePage: {
            items: components["schemas"]["Issue"][];
            next_cursor: components["schemas"]["IssueCursor"] | null;
        };
        IssueUpdate: {
            status: components["schemas"]["IssueStatus"];
            expected_revision: components["schemas"]["NonNegativeDecimalString"];
        };
        Occurrence: {
            record_id: string;
            source_event_id: string | null;
            ingest_seq: components["schemas"]["PositiveDecimalString"];
            occurred_at_us: components["schemas"]["Int64String"];
        };
        OccurrenceCursor: {
            occurred_at_us: components["schemas"]["Int64String"];
            ingest_seq: components["schemas"]["PositiveDecimalString"];
        };
        OccurrencePage: {
            items: components["schemas"]["Occurrence"][];
            next_cursor: components["schemas"]["OccurrenceCursor"] | null;
        };
        /** @description A positive project ID accepted as a decimal string or JSON integer. */
        SearchProjectId: components["schemas"]["PositiveDecimalString"] | number;
        SearchFilters: {
            kinds?: ("log" | "error")[];
            services?: components["schemas"]["SearchFilterValues"];
            levels?: components["schemas"]["SearchFilterValues"];
            environments?: components["schemas"]["SearchFilterValues"];
            releases?: components["schemas"]["SearchFilterValues"];
            loggers?: components["schemas"]["SearchFilterValues"];
        };
        SearchFilterValues: string[];
        SearchRequest: {
            projects?: components["schemas"]["SearchProjectId"][];
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            query?: string;
            filters?: components["schemas"]["SearchFilters"];
            /** @description Defaults to 100 when omitted. */
            limit?: number;
            cursor?: string;
            read_token?: string;
        };
        SearchRow: {
            record_id: string;
            /** @enum {string} */
            kind: "log" | "error";
            project_id: components["schemas"]["PositiveDecimalString"];
            ingest_seq: components["schemas"]["PositiveDecimalString"];
            /** Format: date-time */
            timestamp: string;
            /** Format: date-time */
            received_at: string;
            service: string;
            level: string;
            message: string;
            environment: string | null;
            release: string | null;
            logger: string | null;
            trace_id: string | null;
            span_id: string | null;
            request_id: string | null;
            issue_id: string | null;
            fingerprint: string | null;
            user_id: string | null;
            user_email: string | null;
            detail_token: string;
        };
        SearchPage: {
            rows: components["schemas"]["SearchRow"][];
            next_cursor: string | null;
            read_token: string;
            watermark: components["schemas"]["NonNegativeDecimalString"];
            /** @constant */
            complete: true;
            took_ms: components["schemas"]["NonNegativeDecimalString"];
            searched_shards: components["schemas"]["NonNegativeDecimalString"];
            hydrated_shards: components["schemas"]["NonNegativeDecimalString"];
        };
        RecordDetail: {
            record_id: string;
            raw: unknown;
            detail_token?: string;
        };
        RelatedRecords: {
            reference_record_id: string;
            /** @enum {string} */
            strategy: "trace_id" | "request_id" | "project_service_user_time" | "project_service_error_time";
            exact: boolean;
            window_seconds: number;
            watermark: components["schemas"]["NonNegativeDecimalString"];
            /** @constant */
            complete: true;
            truncated: boolean;
            rows: components["schemas"]["SearchRow"][];
        };
        /** @enum {string} */
        AlertTimeBasis: "received_at" | "timestamp";
        AlertCondition: {
            /** @constant */
            type: "new_issue";
        } | {
            /** @constant */
            type: "regression";
        } | {
            /** @enum {string} */
            type: "error_count" | "log_count";
            query: string;
            window_seconds: number;
            /** Format: uint64 */
            threshold: number;
            cooldown_seconds: number;
            time_basis: components["schemas"]["AlertTimeBasis"];
        };
        AlertDestination: {
            /** @constant */
            type: "webhook";
            /** Format: uri */
            url: string;
        };
        AlertInput: {
            name: string;
            project_id: components["schemas"]["PositiveDecimalString"] | null;
            condition: components["schemas"]["AlertCondition"];
            destination: components["schemas"]["AlertDestination"];
            enabled: boolean;
        };
        AlertUpdate: components["schemas"]["AlertInput"] & {
            /** Format: int64 */
            revision: number;
        };
        Alert: components["schemas"]["AlertInput"] & {
            id: components["schemas"]["PositiveDecimalString"];
            /** Format: int64 */
            revision: number;
            last_evaluation_error: string | null;
            last_evaluation_watermark: components["schemas"]["NonNegativeDecimalString"] | null;
            pending_evaluation_end_us: components["schemas"]["Int64String"] | null;
            pending_cut_seq: components["schemas"]["NonNegativeDecimalString"] | null;
            last_evaluated_at_us: components["schemas"]["Int64String"] | null;
            last_triggered_at_us: components["schemas"]["Int64String"] | null;
            created_at_us: components["schemas"]["Int64String"];
            updated_at_us: components["schemas"]["Int64String"];
        };
        AlertList: {
            items: components["schemas"]["Alert"][];
        };
        AlertDelivery: {
            id: string;
            alert_id: components["schemas"]["PositiveDecimalString"];
            payload: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            state: "pending" | "sent" | "failed" | "cancelled";
            sent_at_us: components["schemas"]["Int64String"] | null;
            last_status_code: number | null;
            attempts: number;
            next_retry_at_us: components["schemas"]["Int64String"];
            created_at_us: components["schemas"]["Int64String"];
            last_error: string | null;
        };
        AlertDeliveryList: {
            items: components["schemas"]["AlertDelivery"][];
        };
        SystemStatus: {
            version: string;
            ready: boolean;
            ingest_accepting: boolean;
            installation_id: string;
            storage_generation: string;
            applied_inbox_id: components["schemas"]["NonNegativeDecimalString"];
            applied_ingest_seq: components["schemas"]["NonNegativeDecimalString"];
            inbox_records: components["schemas"]["NonNegativeDecimalString"];
            inbox_bytes: components["schemas"]["NonNegativeDecimalString"];
            database_bytes: components["schemas"]["NonNegativeDecimalString"];
            wal_bytes: components["schemas"]["NonNegativeDecimalString"];
            disk: {
                total_bytes: components["schemas"]["NonNegativeDecimalString"];
                free_bytes: components["schemas"]["NonNegativeDecimalString"];
                reserved_bytes: components["schemas"]["NonNegativeDecimalString"];
                minimum_free_bytes: components["schemas"]["NonNegativeDecimalString"];
                ingest_accepting: boolean;
            };
            shards: {
                active: components["schemas"]["NonNegativeDecimalString"];
                local: components["schemas"]["NonNegativeDecimalString"];
                remote_verified: components["schemas"]["NonNegativeDecimalString"];
                remote_only: components["schemas"]["NonNegativeDecimalString"];
                records: components["schemas"]["NonNegativeDecimalString"];
                catalog_bytes: components["schemas"]["NonNegativeDecimalString"];
                recoverable_records: components["schemas"]["NonNegativeDecimalString"];
            };
            backup: {
                configured: boolean;
                /** @enum {string} */
                state: "disabled" | "no_checkpoint" | "lagging" | "current";
                latest_checkpoint_id: string | null;
                recoverable_through_ingest_seq: components["schemas"]["NonNegativeDecimalString"] | null;
                lag_records: components["schemas"]["NonNegativeDecimalString"] | null;
            };
            alerts: {
                pending_deliveries: components["schemas"]["NonNegativeDecimalString"];
                failed_deliveries: components["schemas"]["NonNegativeDecimalString"];
                evaluation_failures: components["schemas"]["NonNegativeDecimalString"];
            };
        };
        DoctorReport: {
            /** @constant */
            ok: true;
            schema_version: components["schemas"]["PositiveDecimalString"];
            installation_id: string;
            storage_generation: string;
            checked_local_shards: components["schemas"]["NonNegativeDecimalString"];
            checked_remote_only_shards: components["schemas"]["NonNegativeDecimalString"];
        };
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                request_id: string;
                retryable: boolean;
            };
        };
        AggregateMetricInput: {
            /** @enum {string} */
            op: "count";
            name?: string;
        } | {
            /** @enum {string} */
            op: "sum" | "min" | "max" | "avg";
            name?: string;
            field: string;
        };
        AggregateRequest: {
            projects?: components["schemas"]["SearchProjectId"][];
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            query?: string;
            filters?: components["schemas"]["SearchFilters"];
            read_token?: string;
            metrics?: components["schemas"]["AggregateMetricInput"][];
            group_by?: ("service" | "level" | "environment" | "release")[];
            /** @default 10 */
            group_limit: number;
            histogram?: {
                /** @enum {string} */
                field: "timestamp";
                /** @enum {string} */
                interval: "auto" | "10s" | "1m" | "5m" | "1h" | "6h" | "1d";
            };
        };
        AggregateMetric: {
            name: string;
            /** @enum {string} */
            op: "count";
            value: components["schemas"]["NonNegativeDecimalString"];
            numeric_value_count: null;
        } | {
            name: string;
            /** @enum {string} */
            op: "sum" | "min" | "max" | "avg";
            value: number | null;
            numeric_value_count: components["schemas"]["NonNegativeDecimalString"] | null;
        };
        AggregateBucketKey: {
            /** @enum {string} */
            type: "timestamp";
            timestamp_us: components["schemas"]["Int64String"];
        } | {
            /** @enum {string} */
            type: "string";
            value: string;
        };
        AggregateBucket: {
            key: components["schemas"]["AggregateBucketKey"];
            doc_count: components["schemas"]["NonNegativeDecimalString"];
            metrics: components["schemas"]["AggregateMetric"][];
            children: components["schemas"]["AggregateBucketSet"] | null;
        };
        AggregateBucketSet: {
            dimension: {
                histogram: {
                    interval_ms: number;
                };
            } | {
                group: {
                    /** @enum {string} */
                    field: "service" | "level" | "environment" | "release";
                };
            };
            buckets: components["schemas"]["AggregateBucket"][];
            has_more: boolean;
        };
        AggregateWarning: {
            numeric_exclusion_count_unavailable: {
                metric: string;
                field: {
                    json: string;
                };
            };
        };
        AggregateResponse: {
            record_count: components["schemas"]["NonNegativeDecimalString"];
            metrics: components["schemas"]["AggregateMetric"][];
            buckets: components["schemas"]["AggregateBucketSet"] | null;
            warnings: components["schemas"]["AggregateWarning"][];
            read_token: string;
            watermark: components["schemas"]["NonNegativeDecimalString"];
            /** @constant */
            complete: true;
            took_ms: components["schemas"]["NonNegativeDecimalString"];
            searched_shards: components["schemas"]["NonNegativeDecimalString"];
            hydrated_shards: components["schemas"]["NonNegativeDecimalString"];
        };
        FeedbackPage: {
            items: {
                [key: string]: unknown;
            }[];
        };
        ReplayMetadata: {
            replay_id: string;
            segment_id: number;
            started_at_ms: number;
            finished_at_ms: number;
            user: {
                [key: string]: unknown;
            } | null;
            environment: string | null;
            release: string | null;
            browser: {
                [key: string]: unknown;
            } | null;
            os: {
                [key: string]: unknown;
            } | null;
            device: {
                [key: string]: unknown;
            } | null;
            urls: string[];
            error_ids: string[];
            trace_ids: string[];
            sdk_version: string | null;
            replay_type: string | null;
        };
        ReplayFrustration: {
            slow: number;
            dead: number;
            rage: number;
            multi: number;
        };
        ReplaySummary: {
            project_id: string;
            metadata: components["schemas"]["ReplayMetadata"];
            segment_count: number;
            max_segment_id: number;
            recording_bytes: number;
            partial: boolean;
            frustration: components["schemas"]["ReplayFrustration"];
        };
        ReplayCursor: {
            before_started_ms: number;
            before_id: string;
        };
        ReplayPage: {
            items: components["schemas"]["ReplaySummary"][];
            next_cursor: components["schemas"]["ReplayCursor"] | null;
        };
        ReplayDetail: {
            replay: components["schemas"]["ReplaySummary"];
            segments: {
                segment_id: number;
                compressed_bytes: number;
            }[];
            associations: {
                errors: {
                    event_id: string;
                    record_id: string;
                    issue_id: string;
                }[];
                feedback: {
                    [key: string]: unknown;
                }[];
            };
        };
        ReplayRecording: {
            events: {
                [key: string]: unknown;
            }[];
        };
        ReplayMaps: {
            pages: {
                [key: string]: components["schemas"]["ReplayPageActivity"];
            };
            replays_analyzed: number;
            truncated: boolean;
        };
        ReplayTimelineEvent: {
            timestamp_ms: number;
            kind: string;
            label: string;
            url: string | null;
            duration_ms: number | null;
            event_id: string | null;
            trace_id: string | null;
            span_id: string | null;
        };
        ReplayVisit: {
            url: string;
            started_at_ms: number;
            duration_ms: number | null;
        };
        ReplayPageActivity: {
            visits: number;
            sampled_replays: number;
            observed_time_ms: number;
            timed_visits: number;
            last_observed_replays: number;
            narrow_replays: number;
            wide_replays: number;
            next_pages: {
                [key: string]: number;
            };
            previous_pages: {
                [key: string]: number;
            };
            depth_clicks: {
                [key: string]: number;
            };
            depth_elements: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            replay_ids: string[];
            frustration: components["schemas"]["ReplayFrustration"];
            clicks: {
                [key: string]: number;
            };
            movement: {
                [key: string]: number;
            };
            elements: {
                [key: string]: number;
            };
            max_scroll_viewports: number;
            scroll_samples: number;
            scroll_reach_replays: {
                [key: string]: number;
            };
        };
        ReplayAnalysis: {
            timeline: components["schemas"]["ReplayTimelineEvent"][];
            journey: components["schemas"]["ReplayVisit"][];
            pages: {
                [key: string]: components["schemas"]["ReplayPageActivity"];
            };
            truncated: boolean;
            gaps: number[];
        };
    };
    responses: {
        /** @description Request failed */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        ProjectId: string;
        KeyId: string;
        UserId: string;
        IssueId: components["schemas"]["IssueId"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Administrator created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Session started */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active principal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session ended */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserInput"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResponse"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserInput"];
            };
        };
        responses: {
            /** @description User updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visible projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
            401: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description Project created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResponse"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Project updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listProjectKeys: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active project keys */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ProjectKey"][];
                    };
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    createProjectKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issued key and DSN */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectKey"];
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    revokeProjectKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
                key_id: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listIssues: {
        parameters: {
            query: {
                project_id: components["schemas"]["PositiveDecimalString"];
                status?: components["schemas"]["IssueStatus"];
                limit?: number;
                /** @description Must be paired with cursor_id. */
                cursor_last_seen_us?: components["schemas"]["Int64String"];
                /** @description Must be paired with cursor_last_seen_us. */
                cursor_id?: components["schemas"]["IssueId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stable page ordered by last seen descending and Issue ID ascending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuePage"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue metadata without raw occurrence payloads */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    updateIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueUpdate"];
            };
        };
        responses: {
            /** @description Updated Issue metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listIssueOccurrences: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Must be paired with cursor_ingest_seq. */
                cursor_occurred_at_us?: components["schemas"]["Int64String"];
                /** @description Must be paired with cursor_occurred_at_us. */
                cursor_ingest_seq?: components["schemas"]["PositiveDecimalString"];
            };
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stable page ordered by occurrence time and ingest sequence descending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OccurrencePage"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getIssueOccurrence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Normalized and scrubbed stored occurrence payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordDetail"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
            504: components["responses"]["Error"];
        };
    };
    listLogs: {
        parameters: {
            query: {
                /** @description Comma-separated positive decimal project IDs. Omitted means all active projects visible to the principal. */
                projects?: string;
                start: string;
                end: string;
                query?: string;
                /** @description JSON-encoded SearchFilters object. */
                filters?: string;
                limit?: number;
                cursor?: string;
                read_token?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rows ordered by timestamp and ingest sequence descending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPage"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            410: components["responses"]["Error"];
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
            504: components["responses"]["Error"];
        };
    };
    streamLogs: {
        parameters: {
            query: {
                /** @description Comma-separated positive decimal project IDs. Omitted means all active projects visible to the principal. */
                projects?: string;
                start: string;
                end: string;
                query?: string;
                /** @description JSON-encoded SearchFilters object. */
                filters?: string;
                resume?: string;
            };
            header?: {
                "Last-Event-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE record, checkpoint, resync_required, and error events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            410: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    searchLogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Rows ordered by timestamp and ingest sequence descending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPage"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            410: components["responses"]["Error"];
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
            504: components["responses"]["Error"];
        };
    };
    getRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                detail_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Normalized and scrubbed stored payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordDetail"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            410: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
            504: components["responses"]["Error"];
        };
    };
    getRelatedRecords: {
        parameters: {
            query?: {
                window_seconds?: number;
            };
            header?: never;
            path: {
                detail_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Related records and the correlation strategy actually used */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelatedRecords"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            410: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
            504: components["responses"]["Error"];
        };
    };
    listAlerts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alert configurations visible to an administrator */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertList"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    createAlert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertInput"];
            };
        };
        responses: {
            /** @description Alert created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    deleteAlert: {
        parameters: {
            query: {
                revision: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alert deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    updateAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertUpdate"];
            };
        };
        responses: {
            /** @description Updated alert */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listAlertDeliveries: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent deliveries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertDeliveryList"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    retryAlertDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delivery queued with the same ID */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getSystemStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getSystemDoctor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Consistency report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorReport"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    aggregate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AggregateRequest"];
            };
        };
        responses: {
            /** @description Exact native aggregation for the shared read snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AggregateResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            410: components["responses"]["Error"];
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
            504: components["responses"]["Error"];
        };
    };
    listReplays: {
        parameters: {
            query: {
                project_id: number;
                environment?: string;
                release?: string;
                url?: string;
                user?: string;
                has_error?: boolean;
                rage_click?: boolean;
                dead_click?: boolean;
                min_duration_ms?: number;
                max_duration_ms?: number;
                started_after_ms?: number;
                started_before_ms?: number;
                before_started_ms?: number;
                before_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ReplayPage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayPage"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listFeedback: {
        parameters: {
            query: {
                project_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FeedbackPage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackPage"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getReplayMaps: {
        parameters: {
            query: {
                project_id: number;
                environment?: string;
                release?: string;
                url?: string;
                user?: string;
                has_error?: boolean;
                rage_click?: boolean;
                dead_click?: boolean;
                min_duration_ms?: number;
                max_duration_ms?: number;
                started_after_ms?: number;
                started_before_ms?: number;
                before_started_ms?: number;
                before_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ReplayMaps */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayMaps"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getReplay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: number;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ReplayDetail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayDetail"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    analyzeReplay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: number;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ReplayAnalysis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayAnalysis"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getReplayRecording: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: number;
                id: string;
                segment: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ReplayRecording */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayRecording"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
}
