import type { components } from "../generated/api";

export type ApiErrorBody = components["schemas"]["Error"];
export type SetupState = components["schemas"]["SetupState"];
export type SetupRequest = components["schemas"]["SetupRequest"];
export type Session = components["schemas"]["Session"];
export type SessionTenant = components["schemas"]["SessionTenant"];
export type Project = components["schemas"]["Project"];
export type ProjectList = components["schemas"]["ProjectList"];
export type ProjectCreate = components["schemas"]["ProjectCreate"];
export type ProjectPatch = components["schemas"]["ProjectPatch"];
export type Key = components["schemas"]["Key"];
export type KeyList = components["schemas"]["KeyList"];
export type CreatedKey = components["schemas"]["CreatedKey"];
export type Issue = components["schemas"]["Issue"];
export type IssueList = components["schemas"]["IssueList"];
export type OccurrenceList = components["schemas"]["OccurrenceList"];
export type SDKOutcomeList = components["schemas"]["SDKOutcomeList"];
export type RuleList = components["schemas"]["RuleList"];
export type DeliveryList = components["schemas"]["DeliveryList"];
export type DestinationList = components["schemas"]["DestinationList"];
export type SearchRequest = components["schemas"]["SearchRequest"];
export type SearchResult = components["schemas"]["SearchResult"];
export type AggregateRequest = components["schemas"]["AggregateRequest"];
export type AggregateResult = components["schemas"]["AggregateResult"];
export type QueryJob = components["schemas"]["QueryJob"];
export type RecordDetail = components["schemas"]["RecordDetail"];
export type Kind = components["schemas"]["Kind"];
